# --- Étape 1 : Build (Compilation) ---
FROM gradle:jdk17-alpine AS build
WORKDIR /app

# On copie d'abord les fichiers de config Gradle pour profiter du cache Docker
COPY build.gradle settings.gradle ./
COPY src ./src

# On lance le build sans les tests (pour aller vite ici, les tests sont faits en CI)
RUN gradle bootJar --no-daemon -x test

# --- Étape 2 : Run (Exécution) ---
# On prend une image JRE très légère juste pour lancer Java
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# On récupère le JAR généré à l'étape 1
COPY --from=build /app/build/libs/*.jar app.jar

# On expose le port 8080
EXPOSE 8080

# Commande de lancement
ENTRYPOINT ["java", "-jar", "app.jar"]
