@startuml

skinparam shadowing false
package com.etudlife {
	class com.etudlife.EtudlifeApp {
		--
		+{static} main(args: String[])
	}

	package com.etudlife.model {
		enum com.etudlife.model.NotificationType {
			ANNONCE
			FRIEND_ADDED
			NEW_EVENT
			NEW_MESSAGE
			NEW_RECIPE
			--
		}

		class com.etudlife.model.Lien {
			--
			+Lien()
			+Lien(compteSource: Compte, compteCible: Compte)
			..
			+getCompteCible(): Compte
			+setCompteCible(compteCible: Compte)
			+getCompteSource(): Compte
			+setCompteSource(compteSource: Compte)
			+getDateCreation(): LocalDateTime
			+setDateCreation(dateCreation: LocalDateTime)
			+getId(): Long
			+setId(id: Long)
		}

		class com.etudlife.model.EntreeMenu {
			--
			+EntreeMenu()
			+EntreeMenu(jour: String, moment: String, recette: Recette, utilisateur: Compte)
			..
			+getId(): Long
			+setId(id: Long)
			+getJour(): String
			+setJour(jour: String)
			+getMoment(): String
			+setMoment(moment: String)
			+getRecette(): Recette
			+setRecette(recette: Recette)
			+getUtilisateur(): Compte
			+setUtilisateur(utilisateur: Compte)
		}

		class com.etudlife.model.Message {
			--
			+getContent(): String
			+setContent(content: String)
			+getConversationId(): Long
			+setConversationId(conversationId: Long)
			+getId(): Long
			+setId(id: Long)
			+getReceiverId(): Long
			+setReceiverId(receiverId: Long)
			+getSenderId(): Long
			+setSenderId(senderId: Long)
			+getTimestamp(): LocalDateTime
			+setTimestamp(timestamp: LocalDateTime)
		}

		class com.etudlife.model.Evenement {
			--
			+getCouleur(): String
			+setCouleur(couleur: String)
			+getDateDebut(): LocalDateTime
			+setDateDebut(dateDebut: LocalDateTime)
			+getDateFin(): LocalDateTime
			+setDateFin(dateFin: LocalDateTime)
			+getDescription(): String
			+setDescription(description: String)
			+getId(): Long
			+setId(id: Long)
			+getTitre(): String
			+setTitre(titre: String)
			+getUtilisateur(): Compte
			+setUtilisateur(utilisateur: Compte)
		}

		class com.etudlife.model.Groupe {
			--
			+Groupe()
			+Groupe(nom: String, description: String, categorie: String)
			..
			+getCategorie(): String
			+setCategorie(categorie: String)
			+getDescription(): String
			+setDescription(description: String)
			+getId(): Long
			+setId(id: Long)
			+getMembres(): List<Compte>
			+setMembres(membres: List<Compte>)
			+getNom(): String
			+setNom(nom: String)
			+getPosts(): List<Post>
			+setPosts(posts: List<Post>)
			..
			+ajouterMembre(compte: Compte)
		}

		class com.etudlife.model.Annonce {
			--
		}

		class com.etudlife.model.Post {
			--
			+getAuteur(): Compte
			+setAuteur(auteur: Compte)
			+getContenu(): String
			+setContenu(contenu: String)
			+getDateCreation(): LocalDateTime
			+setDateCreation(dateCreation: LocalDateTime)
			+getGroupe(): Groupe
			+setGroupe(groupe: Groupe)
			+getId(): Long
			+setId(id: Long)
		}

		class com.etudlife.model.LivreBu {
			--
			+getAnnee(): Integer
			+setAnnee(annee: Integer)
			+getAuteur(): String
			+setAuteur(auteur: String)
			+isDisponible(): boolean
			+setDisponible(disponible: boolean)
			+getId(): Long
			+setId(id: Long)
			+getIsbn(): String
			+setIsbn(isbn: String)
			+getPages(): Integer
			+setPages(pages: Integer)
			+getTitre(): String
			+setTitre(titre: String)
		}

		class com.etudlife.model.Recette {
			--
			+Recette()
			+Recette(titre: String, description: String, prixEstime: Double, tempsPreparation: String, categorie: String, ingredients: List<String>, image: String)
			..
			+getCategorie(): String
			+setCategorie(categorie: String)
			+getDescription(): String
			+setDescription(description: String)
			+getId(): Long
			+setId(id: Long)
			+getImage(): String
			+setImage(image: String)
			+getIngredients(): List<String>
			+setIngredients(ingredients: List<String>)
			+getPrixEstime(): Double
			+setPrixEstime(prixEstime: Double)
			+getTempsPreparation(): String
			+setTempsPreparation(tempsPreparation: String)
			+getTitre(): String
			+setTitre(titre: String)
		}

		class com.etudlife.model.CatalogueLivre {
			--
			+getAuteur(): String
			+setAuteur(auteur: String)
			+getCategorie(): String
			+setCategorie(categorie: String)
			+isDisponible(): boolean
			+setDisponible(b: boolean)
			+getTitre(): String
			+setTitre(titre: String)
		}

		class com.etudlife.model.Reservation {
			--
			+getDateRecuperation(): LocalDate
			+setDateRecuperation(dateRecuperation: LocalDate)
			+getDateReservation(): LocalDate
			+setDateReservation(dateReservation: LocalDate)
			+getEmpruntDomicile(): Boolean
			+setEmpruntDomicile(empruntDomicile: Boolean)
			+getId(): Long
			+getIdLivre(): Long
			+setIdLivre(idLivre: Long)
			+getIdUser(): Long
			+setIdUser(idUser: Long)
		}

		class com.etudlife.model.Document {
			--
			+getChemin(): String
			+setChemin(chemin: String)
			+getDateUpload(): Instant
			+setDateUpload(dateUpload: Instant)
			+getDonnees(): byte[]
			+setDonnees(donnees: byte[])
			+getGroupId(): Long
			+setGroupId(groupId: Long)
			+getId(): Long
			+setId(id: Long)
			+getNom(): String
			+setNom(nom: String)
			+getNomFichier(): String
			+setNomFichier(nomFichier: String)
			+getTaille(): long
			+setTaille(taille: long)
			+getType(): String
			+setType(type: String)
			+getUploaderId(): Long
			+setUploaderId(uploaderId: Long)
		}

		class com.etudlife.model.Compte {
			--
			+Compte()
			+Compte(prenom: String, nom: String, email: String, motDePasse: String)
			..
			+getAdresse(): String
			+setAdresse(adresse: String)
			+getBiographie(): String
			+setBiographie(biographie: String)
			+getEmail(): String
			+setEmail(email: String)
			+getGroupes(): List<Groupe>
			+setGroupes(groupes: List<Groupe>)
			+getHobbies(): Set<String>
			+setHobbies(hobbies: Set<String>)
			+getId(): Long
			+setId(id: Long)
			+getLastConnection(): LocalDateTime
			+setLastConnection(lastConnection: LocalDateTime)
			+getLiens(): List<Lien>
			+setLiens(liens: List<Lien>)
			+getMotDePasse(): String
			+setMotDePasse(motDePasse: String)
			+getNom(): String
			+setNom(nom: String)
			+getPosts(): List<Post>
			+setPosts(posts: List<Post>)
			+getPrenom(): String
			+setPrenom(prenom: String)
			+getRecettesFavorites(): Set<Recette>
			+setRecettesFavorites(recettesFavorites: Set<Recette>)
			+getTelephone(): String
			+setTelephone(telephone: String)
		}

		class com.etudlife.model.Notification {
			--
			+Notification()
			+Notification(userId: Long, type: NotificationType, message: String, link: String)
			..
			+getCreatedAt(): LocalDateTime
			+getId(): Long
			+getLink(): String
			+setLink(link: String)
			+getMessage(): String
			+setMessage(message: String)
			+isRead(): boolean
			+setRead(read: boolean)
			+getType(): NotificationType
			+setType(type: NotificationType)
			+getUserId(): Long
			+setUserId(userId: Long)
		}

		class com.etudlife.model.ReservationSalle {
			--
			+getDateReservation(): LocalDate
			+setDateReservation(dateReservation: LocalDate)
			+getDuree(): String
			+setDuree(duree: String)
			+getHeureDebut(): LocalTime
			+setHeureDebut(heureDebut: LocalTime)
			+getId(): Long
			+setId(id: Long)
			+getIdUser(): Long
			+setIdUser(idUser: Long)
			+getNbPersonnes(): Integer
			+setNbPersonnes(nbPersonnes: Integer)
			+getNomComplet(): String
			+setNomComplet(nomComplet: String)
			+getNumeroEtudiant(): String
			+setNumeroEtudiant(numeroEtudiant: String)
			+getZone(): String
			+setZone(zone: String)
		}

	}

	package com.etudlife.dto {
		class com.etudlife.dto.MessageRequestDTO {
			--
			+getContent(): String
			+setContent(content: String)
			+getReceiverId(): Long
			+setReceiverId(receiverId: Long)
			+getSenderId(): Long
			+setSenderId(senderId: Long)
		}

		interface com.etudlife.dto.ConversationPreviewProjection {
			--
			+getContactId(): Long
			+getContactName(): String
			+getConversationId(): Long
			+getLastMessageContent(): String
			+getLastMessageTimestamp(): LocalDateTime
		}

		class com.etudlife.dto.ConversationPreviewDTO {
			--
			+ConversationPreviewDTO(conversationId: Long, contactId: Long, contactName: String, lastMessageContent: String, lastMessageTimestamp: LocalDateTime)
			..
			+getContactId(): Long
			+setContactId(contactId: Long)
			+getContactName(): String
			+setContactName(contactName: String)
			+getConversationId(): Long
			+setConversationId(conversationId: Long)
			+getLastMessageContent(): String
			+setLastMessageContent(lastMessageContent: String)
			+getLastMessageTimestamp(): LocalDateTime
			+setLastMessageTimestamp(lastMessageTimestamp: LocalDateTime)
		}

	}

	package com.etudlife.service {
		class com.etudlife.service.RecetteService {
			--
			+RecetteService(recetteRepository: RecetteRepository, notificationService: NotificationService)
			..
			+getAllRecettes(): List<Recette>
			+getMenuDeLaSemaine(): Map<String,Map<String,Recette>>
			..
			+getRecetteById(id: Long): Recette
			+save(recette: Recette, auteurId: Long, auteurNom: String, prochesIds: List<Long>): Recette
		}

		class com.etudlife.service.LienService {
			--
			+LienService(lienRepository: LienRepository, compteRepository: CompteRepository, notificationService: NotificationService)
			..
			+creerLien(idSource: Long, idCible: Long): Optional<Lien>
			+getLiensPourCompte(idSource: Long): List<Lien>
			+getProcheIds(idSource: Long): List<Long>
			+supprimerLien(idSource: Long, idCible: Long)
		}

		class com.etudlife.service.ConversationService {
			--
			+getOrInitConversationId(user1: Long, user2: Long): Long
			+getPreviewsByUserId(userId: Long): List<ConversationPreviewDTO>
		}

		class com.etudlife.service.EvenementService {
			--
			+add(e: Evenement): Evenement
			+delete(id: Long)
			+getByUserId(id: Long): List<Evenement>
			+getSharedAvailability(myUserId: Long): List<Evenement>
		}

		class com.etudlife.service.GroupeService {
			--
			+GroupeService(groupeRepository: GroupeRepository, compteRepository: CompteRepository)
			..
			+getAllGroupes(): List<Groupe>
			..
			+ajouterMembre(groupeId: Long, compteId: Long): Optional<Groupe>
			+creerGroupe(nom: String, description: String, categorie: String): Groupe
			+getRecommandations(userId: Long): List<Groupe>
		}

		class com.etudlife.service.DocumentService {
			--
			+DocumentService(repo: DocumentRepository)
			..
			+getAllDocuments(): List<Document>
			..
			+enregistrer(fichier: MultipartFile, uploaderId: Long, groupId: Long): Document
			+getDocumentById(id: Long): Optional<Document>
		}

		class com.etudlife.service.MessageService {
			--
			+MessageService(messageRepository: MessageRepository, notificationService: NotificationService)
			..
			+deleteMessage(messageId: Long, userId: Long)
			+getLatestMessages(conversationId: Long): List<Message>
			+getNewMessagesAfter(conversationId: Long, afterId: Long): List<Message>
			+saveNewMessage(conversationId: Long, senderId: Long, receiverId: Long, content: String): Message
		}

		class com.etudlife.service.NotificationService {
			--
			+NotificationService(repo: NotificationRepository)
			..
			+countUnread(userId: Long): long
			+create(userId: Long, type: NotificationType, message: String, link: String): Notification
			+getForUser(userId: Long): List<Notification>
			+markAsRead(id: Long)
		}

		class com.etudlife.service.MenuService {
			--
			+MenuService(menuRepository: EntreeMenuRepository, recetteRepository: RecetteRepository, compteRepository: CompteRepository)
			..
			+genererMenuAutomatique(userId: Long, budgetMax: Double): List<EntreeMenu>
			+getMenuUtilisateur(userId: Long): List<EntreeMenu>
		}

		class com.etudlife.service.CompteService {
			--
			+CompteService(compteRepository: CompteRepository, groupeRepository: GroupeRepository, recetteRepository: RecetteRepository)
			..
			+ajouterFavori(compteId: Long, recetteId: Long)
			+creerCompte(compte: Compte): Compte
			+isUserOnline(userId: Long): boolean
			+lireCompteParId(id: Long): Compte
			+listerComptes(): List<Compte>
			+listerFavoris(compteId: Long): Set<Recette>
			+login(email: String, motDePasse: String): Compte
			+retirerFavori(compteId: Long, recetteId: Long)
			+trouverCompteParNomEtPrenom(nom: String, prenom: String): List<Compte>
			+updatePresence(userId: Long)
		}

		class com.etudlife.service.AnnonceService {
			--
			+AnnonceService(repository: AnnonceRepository)
			..
			+delete(id: Long)
			+findAll(): List<Annonce>
			+findByCategorie(categorie: String): List<Annonce>
			+findById(id: Long): Annonce
			+findByUtilisateurId(utilisateurId: Long): List<Annonce>
			+save(annonce: Annonce): Annonce
		}

		class com.etudlife.service.PostService {
			--
			+PostService(postRepository: PostRepository, compteRepository: CompteRepository, groupeRepository: GroupeRepository)
			..
			+creerPost(auteurId: Long, groupeId: Long, contenu: String): Post
			+getHistoriqueAuteur(auteurId: Long): List<Post>
			+getPostsParGroupe(groupeId: Long): List<Post>
		}

		class com.etudlife.service.ReservationService {
			--
			+annulerReservation(id: Long)
			+getMesReservations(userId: Long): List<Reservation>
			+reserverLivre(livreId: Long, userId: Long): String
			+reserverLivre(livreId: Long, iduser: Long, date: LocalDate, domicile: boolean)
		}

	}

	package com.etudlife.controller {
		class com.etudlife.controller.AnnonceController {
			--
			+AnnonceController(service: AnnonceService, lienRepository: LienRepository, notificationService: NotificationService)
			..
			+create(titre: String, categorie: String, prix: String, ville: String, description: String, auteur: String, utilisateurId: Long, lien: String, image: MultipartFile): Annonce
			+delete(id: Long)
			+getAll(categorie: String): List<Annonce>
			+getById(id: Long): Annonce
			+getByUser(userId: Long): List<Annonce>
			+incrementVue(id: Long): Annonce
			+update(id: Long, titre: String, categorie: String, prix: String, ville: String, description: String, lien: String, image: MultipartFile): Annonce
		}

		class com.etudlife.controller.ConversationController {
			--
			+getConversationPreviews(authenticatedUserId: Long): ResponseEntity<List<ConversationPreviewDTO>>
			+initConversation(authenticatedUserId: Long, contactId: Long): ResponseEntity<Long>
		}

		class com.etudlife.controller.LienController {
			--
			+LienController(lienService: LienService)
			..
			+creerLien(idSource: Long, idCible: Long): Optional<Lien>
			+getProches(idSource: Long): List<Lien>
			+supprimerLien(idSource: Long, idCible: Long)
		}

		class com.etudlife.controller.ReservationController {
			--
			+annuler(id: Long): ResponseEntity<Void>
			+creerReservation(iduser: Long, livreId: Long, dateRecuperation: String, domicile: boolean): ResponseEntity<String>
			+getReservations(userId: Long): ResponseEntity<List<Reservation>>
		}

		class com.etudlife.controller.RecetteController {
			--
			+RecetteController(service: RecetteService)
			..
			+getMenuSemaine(): ResponseEntity<Map<String,Map<String,Recette>>>
			..
			+getRecetteById(id: Long): ResponseEntity<Recette>
		}

		class com.etudlife.controller.MessageController {
			--
			+getMessages(conversationId: Long, afterId: Long): List<Message>
			+sendMessage(conversationId: Long, request: MessageRequestDTO, authenticatedUserId: Long): ResponseEntity<Message>
		}

		class com.etudlife.controller.GlobalMessageController {
			--
			+deleteMessage(id: Long, userId: Long): ResponseEntity<?>
		}

		class com.etudlife.controller.MenuController {
			--
			+MenuController(service: MenuService)
			..
			+generer(payload: Map<String,Object>): ResponseEntity<?>
			+getMenu(userId: Long): List<EntreeMenu>
		}

		class com.etudlife.controller.NotificationController {
			--
			+NotificationController(service: NotificationService)
			..
			+getNotifications(userId: Long): List<Notification>
			+markRead(id: Long)
			+unreadCount(userId: Long): long
		}

		class com.etudlife.controller.EvenementController {
			--
			+ajouter(userId: Long, evenement: Evenement): Evenement
			+getEvenements(userId: Long): List<Evenement>
			+getSharedEvents(userId: Long): List<Evenement>
			+modifier(id: Long, evenementModifie: Evenement): ResponseEntity<Evenement>
			+supprimer(id: Long): ResponseEntity<Void>
		}

		class com.etudlife.controller.GroupeController {
			--
			+GroupeController(groupeService: GroupeService)
			..
			+getAllGroupes(): List<Groupe>
			..
			+ajouterMembre(groupeId: Long, compteId: Long): Groupe
			+creerGroupe(groupe: Groupe): Groupe
			+getRecommandations(userId: Long): List<Groupe>
		}

		class com.etudlife.controller.CompteController {
			--
			+CompteController(compteService: CompteService, compteRepository: CompteRepository)
			..
			+getAllComptes(): List<Compte>
			..
			+ajouterFavori(id: Long, recetteId: Long): ResponseEntity<Void>
			+creerCompte(compte: Compte): ResponseEntity<?>
			+getCompteById(id: Long): Compte
			+getCompteParNomEtPrenom(nom: String, prenom: String): List<Compte>
			+getCompteStatus(id: Long): ResponseEntity<Map<String,Object>>
			+listerFavoris(id: Long): ResponseEntity<Set<Recette>>
			+login(credentials: Map<String,String>): ResponseEntity<?>
			+retirerFavori(id: Long, recetteId: Long): ResponseEntity<Void>
			+signalPresence(userId: Long): ResponseEntity<Void>
			+updateHobbies(id: Long, hobbies: Set<String>): ResponseEntity<?>
			+updateProfil(id: Long, payload: Compte): ResponseEntity<?>
		}

		class com.etudlife.controller.SalleController {
			--
			+annuler(id: Long): ResponseEntity<Void>
			+getMesSalles(userId: Long): List<ReservationSalle>
			+reserver(res: ReservationSalle): ResponseEntity<String>
		}

		class com.etudlife.controller.LivreController {
			--
			+getAllLivres(): List<LivreBu>
			..
			+search(query: String): List<CatalogueLivre>
			+searchInGlobalCatalogue(query: String): List<CatalogueLivre>
		}

		class com.etudlife.controller.PostController {
			--
			+PostController(postService: PostService)
			..
			+creerPost(payload: Map<String,Object>): Post
			+getHistorique(auteurId: Long): List<Post>
			+getPostsParGroupe(groupeId: Long): List<Post>
		}

		class com.etudlife.controller.DocumentController {
			--
			+DocumentController(service: DocumentService)
			..
			+getAllDocuments(): ResponseEntity<?>
			..
			+telechargerDocument(id: Long): ResponseEntity<byte[]>
			+upload(file: MultipartFile, uploaderId: Long, groupId: Long): ResponseEntity<?>
		}

	}

	package com.etudlife.repository {
		interface com.etudlife.repository.EntreeMenuRepository {
			--
			+deleteByUtilisateurId(utilisateurId: Long)
			+findByUtilisateurId(utilisateurId: Long): List<EntreeMenu>
		}

		interface com.etudlife.repository.DocumentRepository {
			--
			+findByNomAndUploaderId(nom: String, uploaderId: Long): Optional<Document>
		}

		interface com.etudlife.repository.CompteRepository {
			--
			+findAllByNomIgnoreCaseAndPrenomIgnoreCase(nom: String, prenom: String): List<Compte>
			+findByEmail(email: String): Optional<Compte>
		}

		interface com.etudlife.repository.GroupeRepository {
			--
		}

		interface com.etudlife.repository.MessageRepository {
			--
			+findByConversationIdAndIdGreaterThanOrderByTimestampAsc(conversationId: Long, afterId: Long): List<Message>
			+findConversationIdByParticipants(user1: Long, user2: Long): Long
			+findConversationPreviewsByUserId(userId: Long): List<ConversationPreviewProjection>
			+findTop50ByConversationIdOrderByTimestampDesc(id: Long): List<Message>
		}

		interface com.etudlife.repository.LienRepository {
			--
			+deleteByCompteSourceIdAndCompteCibleId(idSource: Long, idCible: Long)
			+existsByCompteSourceIdAndCompteCibleId(sourceId: Long, cibleId: Long): boolean
			+findByCompteSourceId(compteSourceId: Long): List<Lien>
		}

		interface com.etudlife.repository.ReservationRepository {
			--
			+findByIdUser(idUser: Long): List<Reservation>
		}

		interface com.etudlife.repository.EvenementRepository {
			--
			+findByUtilisateurId(utilisateurId: Long): List<Evenement>
			+findByUtilisateurIdIn(utilisateurIds: List<Long>): List<Evenement>
		}

		interface com.etudlife.repository.LivreBuRepository {
			--
			+findByDisponibleTrue(): List<LivreBu>
		}

		interface com.etudlife.repository.PostRepository {
			--
			+findByAuteurIdOrderByDateCreationDesc(auteurId: Long): List<Post>
			+findByGroupeIdOrderByDateCreationDesc(groupeId: Long): List<Post>
		}

		interface com.etudlife.repository.CatalogueRepository {
			--
			+findByTitreContainingIgnoreCaseOrAuteurContainingIgnoreCaseOrCategorieContainingIgnoreCase(titre: String, auteur: String, categorie: String): List<CatalogueLivre>
		}

		interface com.etudlife.repository.NotificationRepository {
			--
			+countByUserIdAndIsReadFalse(userId: Long): long
			+findByUserIdOrderByCreatedAtDesc(userId: Long): List<Notification>
		}

		interface com.etudlife.repository.RecetteRepository {
			--
			+findByPrixEstimeLessThanEqual(prixMax: Double): List<Recette>
		}

		interface com.etudlife.repository.ReservationSalleRepository {
			--
			+findByIdUser(idUser: Long): List<ReservationSalle>
		}

		interface com.etudlife.repository.AnnonceRepository {
			--
			+findByCategorie(categorie: String): List<Annonce>
			+findByUtilisateurId(utilisateurId: Long): List<Annonce>
		}

	}

}

com.etudlife.model.Lien "*" o--* "2" com.etudlife.model.Compte
com.etudlife.model.EntreeMenu --* com.etudlife.model.Recette
com.etudlife.model.EntreeMenu --* com.etudlife.model.Compte
com.etudlife.model.Evenement --* com.etudlife.model.Compte
com.etudlife.model.Groupe "*" o--o "*" com.etudlife.model.Compte
com.etudlife.model.Groupe *--o "*" com.etudlife.model.Post
com.etudlife.model.Post "*" o--* com.etudlife.model.Compte
com.etudlife.model.Compte --o "*" com.etudlife.model.Recette
com.etudlife.model.Notification --* com.etudlife.model.NotificationType
com.etudlife.service.RecetteService --* com.etudlife.repository.RecetteRepository
com.etudlife.service.RecetteService --* com.etudlife.service.NotificationService
com.etudlife.service.LienService --* com.etudlife.repository.LienRepository
com.etudlife.service.LienService --* com.etudlife.repository.CompteRepository
com.etudlife.service.LienService --* com.etudlife.service.NotificationService
com.etudlife.service.ConversationService --* com.etudlife.repository.MessageRepository
com.etudlife.service.EvenementService --* com.etudlife.repository.EvenementRepository
com.etudlife.service.EvenementService --* com.etudlife.service.NotificationService
com.etudlife.service.EvenementService --* com.etudlife.service.LienService
com.etudlife.service.GroupeService --* com.etudlife.repository.GroupeRepository
com.etudlife.service.GroupeService --* com.etudlife.repository.CompteRepository
com.etudlife.service.DocumentService --* com.etudlife.repository.DocumentRepository
com.etudlife.service.MessageService --* com.etudlife.repository.MessageRepository
com.etudlife.service.MessageService --* com.etudlife.service.NotificationService
com.etudlife.service.NotificationService --* com.etudlife.repository.NotificationRepository
com.etudlife.service.MenuService --* com.etudlife.repository.EntreeMenuRepository
com.etudlife.service.MenuService --* com.etudlife.repository.RecetteRepository
com.etudlife.service.MenuService --* com.etudlife.repository.CompteRepository
com.etudlife.service.CompteService --* com.etudlife.repository.CompteRepository
com.etudlife.service.CompteService --* com.etudlife.repository.GroupeRepository
com.etudlife.service.CompteService --* com.etudlife.repository.RecetteRepository
com.etudlife.service.AnnonceService --* com.etudlife.repository.AnnonceRepository
com.etudlife.service.PostService --* com.etudlife.repository.PostRepository
com.etudlife.service.PostService --* com.etudlife.repository.CompteRepository
com.etudlife.service.PostService --* com.etudlife.repository.GroupeRepository
com.etudlife.service.ReservationService --* com.etudlife.repository.ReservationRepository
com.etudlife.service.ReservationService --* com.etudlife.repository.LivreBuRepository
com.etudlife.controller.AnnonceController --* com.etudlife.service.AnnonceService
com.etudlife.controller.AnnonceController --* com.etudlife.repository.LienRepository
com.etudlife.controller.AnnonceController --* com.etudlife.service.NotificationService
com.etudlife.controller.ConversationController --* com.etudlife.service.ConversationService
com.etudlife.controller.LienController --* com.etudlife.service.LienService
com.etudlife.controller.ReservationController --* com.etudlife.service.ReservationService
com.etudlife.controller.RecetteController --* com.etudlife.service.RecetteService
com.etudlife.controller.MessageController --* com.etudlife.service.MessageService
com.etudlife.controller.GlobalMessageController --* com.etudlife.service.MessageService
com.etudlife.controller.MenuController --* com.etudlife.service.MenuService
com.etudlife.controller.NotificationController --* com.etudlife.service.NotificationService
com.etudlife.controller.EvenementController --* com.etudlife.repository.EvenementRepository
com.etudlife.controller.EvenementController --* com.etudlife.repository.CompteRepository
com.etudlife.controller.EvenementController --* com.etudlife.service.EvenementService
com.etudlife.controller.EvenementController --* com.etudlife.service.LienService
com.etudlife.controller.GroupeController --* com.etudlife.service.GroupeService
com.etudlife.controller.CompteController --* com.etudlife.service.CompteService
com.etudlife.controller.CompteController --* com.etudlife.repository.CompteRepository
com.etudlife.controller.SalleController --* com.etudlife.repository.ReservationSalleRepository
com.etudlife.controller.LivreController --* com.etudlife.repository.LivreBuRepository
com.etudlife.controller.LivreController --* com.etudlife.repository.CatalogueRepository
com.etudlife.controller.PostController --* com.etudlife.service.PostService
com.etudlife.controller.DocumentController --* com.etudlife.service.DocumentService

@enduml
