name: Update UML Diagram

on:
  push:
    branches:
      - master
    paths:
      - 'backend/src/main/java/**'
      - 'backend/build.gradle'

permissions:
  contents: write

jobs:
  generate-uml:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Rendre gradlew exécutable (dans le bon dossier)
      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      # 4. Générer le diagramme PlantUML (.puml) via Gradle
      - name: Generate UML Diagram
        working-directory: ./backend
        run: ./gradlew buildClassDiagram

      - name: Generate Image from PlantUML
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: doc/diagram_model.puml # Indique où se trouve ton fichier généré

      # 6. Commiter et Pusher le changement (PUML + Images)
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update UML diagram & images automatically 🤖"
          # On sauvegarde le puml, mais aussi les images générées dans le dossier doc/
          file_pattern: 'doc/diagram_model.puml doc/*.png doc/*.svg'